# Generated by Django 3.2.5 on 2021-09-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='医生姓名')),
                ('iddentificationID', models.CharField(max_length=255, unique=True, verbose_name='医生身份证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='医生建档时间')),
            ],
            options={
                'verbose_name': '医生',
                'verbose_name_plural': '医生集',
            },
        ),
    ]
