# Generated by Django 3.2.5 on 2021-09-14 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologypictureitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='图片描述'),
        ),
        migrations.AlterField(
            model_name='pathologypictureitem',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.patient', verbose_name='患者'),
        ),
    ]
