# Generated by Django 3.2.5 on 2021-09-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0002_alter_patient_otherdoctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='otherDoctors',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='其他剖验医生'),
        ),
    ]
