# Generated by Django 3.2.5 on 2021-09-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0002_auto_20210914_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
    ]
