# Generated by Django 3.2.5 on 2021-09-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0003_pathologypicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='operateRecord',
            field=models.FileField(null=True, upload_to='records', verbose_name='解剖记录'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pptRecord',
            field=models.FileField(null=True, upload_to='ppt', verbose_name='纠纷PPT'),
        ),
    ]
