# Generated by Django 3.2.5 on 2021-10-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0003_alter_patient_otherdoctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='iddentificationID',
        ),
        migrations.AlterField(
            model_name='patient',
            name='otherDocument',
            field=models.FileField(blank=True, null=True, upload_to='otherdocs', verbose_name='其他文档'),
        ),
    ]
