# Generated by Django 3.2.5 on 2021-10-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0004_auto_20211015_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='iddentificationID',
        ),
        migrations.AddField(
            model_name='patient',
            name='bodySource',
            field=models.CharField(choices=[('DE', '遗体捐献'), ('DI', '医疗纠纷')], default='DI', max_length=2, verbose_name='遗体来源'),
        ),
    ]
