# Generated by Django 3.2.5 on 2021-10-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0005_auto_20211015_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
