# Generated by Django 3.2.5 on 2021-11-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0007_alter_pathologypictureitem_pathologypicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologypictureitem',
            name='bigPathologyPicture',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='大病理图片'),
        ),
        migrations.AlterField(
            model_name='pathologypictureitem',
            name='pathologyPicture',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='病理图片'),
        ),
    ]
