# Generated by Django 3.2.5 on 2021-11-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0008_auto_20211130_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathologypictureitem',
            name='bigPathologyPicture',
            field=models.FileField(blank=True, help_text='size >= 1G的图片或无法正常显示的图片', null=True, upload_to='images', verbose_name='大病理图片'),
        ),
        migrations.AlterField(
            model_name='pathologypictureitem',
            name='pathologyPicture',
            field=models.ImageField(blank=True, help_text='size < 1G的图片', null=True, upload_to='images', verbose_name='病理图片'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='年龄'),
        ),
    ]
