# Generated by Django 3.2.5 on 2021-12-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0009_auto_20211130_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photoNum',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='照片数'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pptNum',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='幻灯片数'),
        ),
        migrations.AddField(
            model_name='patient',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sliceNum',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='切片数'),
        ),
    ]
